import localFont from "next/font/local";
import { Baloo_2 } from "next/font/google";
import "./globals.css";

const baloo = Baloo_2({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Learn Maths with Fun",
  description: "Generated by Python Maths Web App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={baloo.className}>
        {children}
      </body>
    </html>
  );
}
